### ISSUE TITLE
Provide example of state graph

### ISSUE THREAD

**Issue by Swatinem** [evancz/guide.elm-lang.org#1]
Hi!

When reading the docs for Elm or other functional and/or immutable alternatives, all the examples deal with a state *tree*. But in reality, the state is more like a *graph* with *a lot* of edges between different nodes.

As a newcomer I have a hard time to wrap my head around how to achieve something like this in a language like elm. Or more precisely, how to do it in a way that is both convenient and high performance. 

Ideally without having to pass a *registry* down through all my components, and without having all my components rerender when the registry changes.

It would be really nice to have such an example in the official guide :-)

**Comment by evancz** [comment]
Thanks for the suggestion. I don't think there will be a section on this in the guide as I disagree about what reality is really like, but it makes sense to talk through this on elm-discuss or the Elm slack channel with other community members. http://elm-lang.org/community
