### ISSUE TITLE
Simplify Buttons for true beginners

### ISSUE THREAD

**Issue by willnwhite** [evancz/guide.elm-lang.org#10]
The code in [the example](http://elm-lang.org/examples/buttons) (which [the Buttons page](http://guide.elm-lang.org/architecture/user_input/buttons.html) links to) is nicer for a beginner to see than the code on the Buttons page, because it introduces the Elm Architecture (the focus) without types. One thing, instead of two things to learn at once. 

I'll try to put my specific comments in my pull request.

**Comment by willnwhite** [comment]
I've found a nice place to introduce types is in Forms, when you write your own function (`viewValidation`) for the first time.

**Comment by evancz** [comment]
Whenever I take the types away, someone does not like it.

Whenever I add the types back, someone does not like it.

I think really addressing this requires work on the structure of the book itself. I don't think there is a quick fix. Other authors are finding ways to introduce these concepts more gradually. Sometimes we disagree about the particular time. I tend to prefer that people see them but learn to just ignore them to some extent. Maybe it can be done better. It's not a simple change though.
