### ISSUE TITLE
making a little less confusing the documentation

### ISSUE THREAD

**Issue by Grummfy** [evancz/guide.elm-lang.org#101]
Hi,
I really enjoy tyhe clarity of the documentation, but the example can be less confusiong just by renaming stuff.

Here is an example:
https://guide.elm-lang.org/architecture/effects/random.html and the given example 
http://elm-lang.org/examples/random

=> https://ellie-app.com/39M4FDKfwz5a1/1

So just by renaming some values, we make it more explicit :
* no more risk of misinterpretation that we always need to have a view, update or init function inside a model
* a model can be named something else than Model
* variable name doesn't require to be the model name in lowcapse
* wherever I'm inside the code, the name of variable are a bit more explicit (following if you are familiar wit English or not)

After that, we can always said that it's better to have update, init, etc function to be easier to read. But learning with that make confusion possible.

It's just a suggestion, but it can help people to understand faster the given example all along the documentation, so increase the adoption of elm ;) What do you think of this?

**Comment by evancz** [comment]
I want to keep it as it is. I like the idea of making it clearer to folks that the function names can be whatever you want, but I think I care more that there is a general culture where folks do things in similar ways, making it easy to read other people's code. Perhaps there is some other way to accomplish the root goal.
