### ISSUE TITLE
Recursion in union types section risks stack blow?

### ISSUE THREAD

**Issue by paultopia** [evancz/guide.elm-lang.org#102]
Hi there, 

I've been reading through the Elm guide---apologies if I misunderstand how the language works and this is a silly issue.  But it seems to me that the linked list example in the Union Types section is a little sub-optimal, because the function to sum a linked list isn't tail recursive, & hence could blow the stack (I assume the elm compiler does TCO but doesn't have any truly amazing black magic to optimize away non-tail recursive calls...). 

Of course, experienced functional programmers will know to use a reduce (uh... fold, right? It's fold in ML-like languages?  I'm mostly a Clojure guy...) or a tail call version, but the rest of the example reads as if it's written for people who aren't comfortable with recursion ("It can be tricky to get into the mindset of writing recursive functions, so I wanted to share one weird trick"), and hence might get bitten if they play around with this code for long lists.  

Maybe it's worth either rewriting the function or adding a note about tail calls and runtime errors in there?

**Comment by evancz** [comment]
I just wanted to show the simplest version. I have some other documentation that introduces tail-call optimization.

Anyway, in the latest version of the book, this section did not make it!
