### ISSUE TITLE
Show how to pass objects through ports

### ISSUE THREAD

**Issue by willnwhite** [evancz/guide.elm-lang.org#12]
The reason I haven't used Elm (and went off back to JavaScript) is because I didn't know if I could use a certain library (BigRational.js) with Elm that is critical for my application (dividing and then adding money). This library sends objects, and I'm guessing many do, and from what I gather passing them through ports isn't quite as simple as passing strings or even lists of strings.

**Comment by evancz** [comment]
You can pass objects (called records in Elm) through ports. It mentions it [here](http://guide.elm-lang.org/interop/javascript.html#customs-and-border-protection). You can also pass arbitrary JSON values through.

Ask on the Elm slack channel (http://elm-lang.org/community) for more guidance. The docs can be improved, but it'll be faster to talk to a community member!

**Comment by willnwhite** [comment]
I was confused because it seemed as if `{}` was a type like `List String` was a type, as it was working in type annotations and the program was compiling. However, my screen looked like this:
![screen shot 2016-07-07 at 11 23 34](https://cloud.githubusercontent.com/assets/8081877/16650870/4ff231fa-4438-11e6-9b4f-eb928311b8b1.png)
when I wanted it to look like this:
![screen shot 2016-07-07 at 11 47 04](https://cloud.githubusercontent.com/assets/8081877/16650902/9085cac4-4438-11e6-8600-c9c5f2ecf9ab.png)
The missing piece was this:
![screen shot 2016-07-07 at 11 42 43](https://cloud.githubusercontent.com/assets/8081877/16650913/9ca4904c-4438-11e6-88cf-ec3c9b3319ea.png)

**Comment by evancz** [comment]
The values you pass in may have additional fields, but Elm will not know about them.

So if you say you are getting `{}` you get a record with no fields. It is similar to `()` in Elm. If you say `{ denom: {} }` it will ensure that you have a `denom` field and that it is an object of some sort.
