### ISSUE TITLE
Different code in the guide and online editor

### ISSUE THREAD

**Issue by fadawar** [evancz/guide.elm-lang.org#129]
There are small differences between the examples in the text of the guide and in online editor.

Example:
https://guide.elm-lang.org/architecture/user_input/buttons.html
```elm
-- MODEL

type alias Model = Int

model : Model
model =
  0
```

http://elm-lang.org/examples/buttons
```elm
-- MODEL

model = 0
```

Not a big problem, but it would be nice to have it in sync.

**Comment by evancz** [comment]
With the new version of book, the examples in the editor match the book exactly.
