### ISSUE TITLE
Embed the program you're building at top of tutorial page

### ISSUE THREAD

**Issue by willnwhite** [evancz/guide.elm-lang.org#13]
This means the reader can spontaneously try to implement the program themselves (because they know what it looks like), rather than just following the tutorial. At the moment the program is a click away ("See online") so this is less likely. I know I tended not to click the "See online" link on my first run through.

**Comment by evancz** [comment]
I don't think gitbook allows iframes, so I don't know how to do this. If you have links to a way to achieve it, please share a link about it!
