### ISSUE TITLE
Time: seconds hand is a quarter turn fast

### ISSUE THREAD

**Issue by nickcernis** [evancz/guide.elm-lang.org#130]
Really enjoying the guide so far! The time exercise tripped me up, though:

The default clock hand in the [time example](https://github.com/evancz/guide.elm-lang.org/blob/master/architecture/effects/time.md) does not reflect the number of seconds for the current browser/system time. It's a quarter turn fast, as visible in the [live example](http://elm-lang.org/examples/time):

![time-in-seconds](https://user-images.githubusercontent.com/647669/42420570-ed8b72d0-82c7-11e8-942d-a7b3404d232f.png)

`angle` is given as:

```elm
angle =
    turns (Time.inMinutes model)
```

This would make it correct:

```elm
angle =
    turns (Time.inMinutes model) - turns 0.25
```

I also struggled to see at first why `Time.inMinutes` was being used to calculate the angle of the _second_ hand.

I [solved the exercises](https://ellie-app.com/JGXW4v2rnna1), but it seems possible to get lost along the way figuring out how the angle is derived.

It might be clearer to express seconds from the current time using the Date library:

```elm
    date =
        fromTime model

    seconds =
        toFloat (Date.second date)

    angle =
        -- Remove a quarter turn because 0 turns points to three o'clock.
        turns (seconds / 60) - turns 0.25
```

That may be easier for a beginner to extend for the hour and minute hands (even though hours will always be a whole number, so the hour hand won't creep forward throughout the hour).

Or it could be that showing how time subscriptions work using a digital clock face would introduce fewer concepts at once (SVG, trigonometry, radians/turns…).

**Comment by evancz** [comment]
The current version of the example does not use SVG anymore. That is left as an exercise.
