### ISSUE TITLE
Improve digital clock example display

### ISSUE THREAD

**Issue by FranklinChen** [evancz/guide.elm-lang.org#137]
I noticed that the digital clock example display shows times like `18:6:5`. I know the niceties of time formatting are not the purpose of the example, which is to show how subscriptions work, but given that readers know how clocks are supposed to look, it is probably a distraction that the time is not formatted correctly to `18:06:05`. Maybe add a helper function to add the leading zero to minutes and seconds, and also add a note on how using only `String.fromInt` may lead to awkward user interface glitches in apps?

**Comment by evancz** [comment]
I would want to see a person learning Elm go through this to see how they react before changing it.
