### ISSUE TITLE
Provide answers to exercises

### ISSUE THREAD

**Issue by willnwhite** [evancz/guide.elm-lang.org#15]
It's nice to know you came up with an idiomatic solution.

**Comment by adamwiggall** [comment]
I'll second this, especially with the forms page. Seeing how to add extra validations in an idiomatic way would be very useful (from the author of the language no less).

**Comment by gabehollombe** [comment]
👍  I'd love to see suggested solutions as well.  To @adamwiggall's point above, here's how I added the validations. No idea if this is idiomatic or not: https://gist.github.com/gabehollombe/45cb6f61ccb270931ded71f155ca37fe

**Comment by evancz** [comment]
Tracking in #93!
