### ISSUE TITLE
"chabudai" is not alternative to chairs

### ISSUE THREAD

**Issue by arowM** [evancz/guide.elm-lang.org#158]
I know it's trivial and does not improve content itself any more, but "chabudai" is not alternative to chairs.
The term "chabudai", it seems it means Japanese word "ちゃぶ台", is used as an alternative to chairs in `book/optimization/lazy.md`.
But actually it is a kind of table, so sitting on a chabudai as a chair is a sort of bad manner ;)

[![chabudai](https://user-images.githubusercontent.com/1481749/46779444-c91e0400-cd52-11e8-8bb7-3affc9fa594a.jpg)](https://ja.wikipedia.org/wiki/%E3%81%A1%E3%82%83%E3%81%B6%E5%8F%B0)

I suggest to use "zaisu" (座椅子) instead.
[![zaisu](https://www.irisplaza.co.jp/image/interior/scene/9506111F_1.jpg)](https://www.irisplaza.co.jp/index.php?KB=SHOSAI&SID=9506111F)

Sorry for useless issue.

- My mother tongue is Japanese
- I want to learn Elm because its goal is not to be a general great language, but to be a sort of DSL for creating reliable web apps
- I was confused that "the function name implies that chabudai is alternative to chair but actually it isn't..."

**Comment by evancz** [comment]
The goal is not to say that you sit on the table. The idea is that a neat alternative to chairs is not having chairs. You can just sit on the floor. You can just sit at a low table. That kind of thing. I thought it would be nice for people to search around for these terms if they hadn't seen them before.

I would be curious to know which interpretation is more apparent for people coming from other backgrounds.

**Comment by arowM** [comment]
It makes sense. Thanks for sincere reply!
