### ISSUE TITLE
String.reverse call in view in the text fields page is not idiomatic

### ISSUE THREAD

**Issue by kjivan** [evancz/guide.elm-lang.org#183]
Please fill in the following information:

- My programming background is software engineer
- I want to learn Elm because it looks like a great language and I want to get into web development
- I was confused by the fact that you manipulate data in the view. Traditionally you try not to manipulate data in the view. I would think you would want to change data in the update method. However, in the text field explanation in the elm-guide you change data in the view.  Maybe I am misunderstanding something or there is a reason why that would be preferred.

> **Note:** The answers do not have to be super elaborate. I just need to understand who is confused and why. As I learn more about the readers, it is possible to revamp the book that addresses their concerns in a coherent way. Ultimately I must pick an audience, so it fundamentally cannot work for everyone. Choices must be made!

**Comment by evancz** [comment]
I think this question would work better for https://discourse.elm-lang.org or https://www.reddit.com/r/elm/ or https://elmlang.herokuapp.com where people can give more detailed feedback.

The short answer is that the customs and best practices in traditional MVC frameworks do not always translate directly into a functional setting for a big variety of reasons.
