### ISSUE TITLE
Installation step: npm: struggling

### ISSUE THREAD

**Issue by frozar** [evancz/guide.elm-lang.org#198]
I'm new to Elm and delightful web programming interest me a lot, so thank you. Maybe this issue is not at the right place and I apologize in advance for that.

I follow instruction from the guide to install Elm. I'm under Ubuntu 16.04 so I choose npm to install it. The command `sudo npm install -g elm` gives me a confusing error about access rights. My issue is described and solved on this post:
https://stackoverflow.com/questions/44878798/permission-denied-error-while-attempting-to-install-elm-with-sudo-on-ubuntu

_My question is:_
Is it possible to add the command `sudo npm install --unsafe-perm -g elm` in the [Troubleshooting section](https://www.npmjs.com/package/elm#troubleshooting) of the npm elm package? (or in the place of your choice)

The purpose is to find this command quickly and avoid an annoying first step issue.

**Comment by evancz** [comment]
I recently changed the guide to not point to npm at all. The instructions [here](https://guide.elm-lang.org/install/terminal.html) take Linux users to instructions that do not use npm at all, avoiding the problems that some fraction of folks run into with npm.
