### ISSUE TITLE
HTTP guide section: mismatch init snippet

### ISSUE THREAD

**Issue by frozar** [evancz/guide.elm-lang.org#199]
In the [HTTP page of the guide](https://guide.elm-lang.org/effects/http.html), the URL of the global example doesn't match with the one given in the snippet code.

Global example:
```elm
[...]
init : () -> (Model, Cmd Msg)
init _ =
  ( Loading
  , Http.get
      { url = "https://elm-lang.org/assets/public-opinion.txt"
      , expect = Http.expectString GotText
      }
  )
[...]
```

The snippet code:
```elm
init : () -> (Model, Cmd Msg)
init _ =
  ( Loading
  , Http.get
      { url = "http://www.gutenberg.org/cache/epub/6456/pg6456.txt"
      , expect = Http.expectString GotText
      }
  )
```

IMHO, you should keep the first link:
https://elm-lang.org/assets/public-opinion.txt

**Comment by evancz** [comment]
It looks like both the guide and the example use the elm-lang.org link in the latest version of the guide. This is necessary to avoid CORS issues. So I believe it is as you suggest now!
