### ISSUE TITLE
Convert to mdBook

### ISSUE THREAD

**Issue by heyakyra** [evancz/guide.elm-lang.org#209]
Since gitbook has gone proprietary and the free software version is no longer maintained https://github.com/rust-lang-nursery/mdBook might be a nice thing to switch to

**Comment by evancz** [comment]
I switched to using the last release of the npm package for now, but I have been thinking of finding something new such that I could add a couple things:

- inline REPL for folks just getting started (maybe can be done with an iframe)
- different paths for different backgrounds (e.g. web dev, data science, new programmer)

The first big hurdle is getting a REPL working in browser though, so I'm planning to revisit this after that. I'll keep this open as a possibility! Thanks :)

**Comment by heyakyra** [comment]
> inline REPL for folks just getting started (maybe can be done with an iframe)

Would using https://github.com/ellie-app/ellie work?

```
<iframe src="https://ellie-app.com/embed/6wDykBpjvwka1" style="width:100%; height:400px; border:0; overflow:hidden;" sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"></iframe>
```

> different paths for different backgrounds (e.g. web dev, data science, new programmer)

Not sure what you mean here, you could have different chapters which would result in different url paths, or you could compile multiple books and tweak the CI config to build them properly.

**Comment by evancz** [comment]
I am thinking of something like http://elmrepl.cuberoot.in/ but where I can embed it on the https://guide.elm-lang.org/core_language.html page in particular.

**Comment by evancz** [comment]
I got the REPL working in the book! I am pretty happy using the gitbook command line tool. I'm not having any problems, so I think I'll be fine using the last release of it for a while.
