### ISSUE TITLE
No mention of packages or imports when needed

### ISSUE THREAD

**Issue by emanchado** [evancz/guide.elm-lang.org#21]
When following the guide and reaching the HTTP exercise there's no mention of `elm-package`, which package should be installed, the instructions to install it, or the import that should be added to the source file.

It's of course not very hard to figure out, but it kind of breaks the flow of doing the exercises while reading the guide. There's a similar problem with the WebSockets example, and maybe some other.

And especially since http://incolumitas.com/2016/06/08/typosquatting-package-managers/, it would be nice to make sure people cannot mistakenly install the wrong package, or even wonder how to install the correct one :-)

Anyway, great guide otherwise and great language!

**Comment by evancz** [comment]
The guide was recently revised and tries to include this sort of information before each example. E.g. https://guide.elm-lang.org/effects/http.html
