### ISSUE TITLE
No undefined is not a function

### ISSUE THREAD

**Issue by markhdavid** [evancz/guide.elm-lang.org#210]
Hi, I've been programming for a few decades, lots of Lisp, some functional. I've done some hacking in javascript, but not a lot. I've done bits of web programming for my hobby sites.  I want to redo some of my hobby sites in a modern language, and also may want to get some professional work down the line, and I've heard great things about Elm, so I just jumped in and found this guide.

I got stuck on this sentence near the beginning

No `undefined` is not a function.

I did not know how to parse this.  As written, it apparently makes the proposition that "undefined" is always a function.  If no 'undefined' is not a function, then every 'undefined' is a function. But, after a short time, I thought that makes too little sense, particularly in the bullet point that begins "No runtime errors in practice."  

Then, I thought it was meant to read

No: 'undefined' is **not** a function.

So, I googled to search for evidence that some other languages (presumably Javascript) have a function named 'undefined'. But I could not find evidence that this is the case.

Finally, I googled "undefined is not a function", and found lots of results with a title like this:

Uncaught TypeError: undefined is not a function

or

Uncaught TypeError: 'undefined' is not a function

Aha, so now I realized that what is meant is that there's a commonly encountered error message that includes this text:

`'undefined' is not a function`

And you mean Elm doesn't have that. So, how about writing it this way:

No `'undefined' is not a function`.

I.e., the idea is to clearly identify the entire phrase "'undefined' is not a function" as the thing there's none of.

**Comment by evancz** [comment]
I recently made some edits to the first page, and this phrase did not make it through. I couldn't figure out how to resolve the confusion you had, and decided it seemed to read alright without it!
