### ISSUE TITLE
Function call syntax is not C-style. Hint would help!

### ISSUE THREAD

**Issue by emanchado** [evancz/guide.elm-lang.org#22]
I'm a total Elm n00b, and only tried to learn Haskell many years ago and failed miserably... but I'm guessing many other people are in the same situation so I don't think the following suggestion is too crazy. Anyway.

I found myself longing for a description of the language syntax, I think for the first time in my life. It's super nice that the tutorial gets you to do practical, useful stuff right away, but the syntax felt a bit daunting sometimes. I just didn't understand what certain things meant, and had to copy-paste blindly.

I think explicitly mentioning these two small things would have helped me:
- Function parameters _don't_ use comma, but lists do
- As function parameters aren't separated by commas, you need parenthesis when one of the parameters in an expression

One of the problems is that the isNegative function only has one parameter, so it's not evident. It's maybe enough with making the function receive two parameters, and possibly adding a note pointing it out.

**Comment by emanchado** [comment]
Again, it's something you realise yourself after a little bit, so maybe you want to let people realise while modifying the examples or similar. However, for people who are not necessarily interested in learning other languages, but just need to learn Elm quickly, it would be very useful.

**Comment by evancz** [comment]
Tracking in #93. Sorry for the confusion, and thanks for letting me know your experience!
