### ISSUE TITLE
Repl not working correctly with scandic keyboard layout

### ISSUE THREAD

**Issue by peksipatongeis** [evancz/guide.elm-lang.org#225]
Please fill in the following information:

- My programming background is in JavaScript and React
- I want to learn Elm because I want be more confident in refactoring front end
- I was confused by Repl not working properly with a scandic keyboard layout. Not being able to type `[]{}` characters in the interactive examples is quite an inconvenience.

**Comment by evancz** [comment]
[The code](https://github.com/evancz/guide.elm-lang.org/blob/master/repl/src/Repl.elm#L420-L448) that adds characters should just pass them along independent of keyboard layout. It is using `event.key` behind the scenes.

Do you have any ideas of how I could reproduce this?

Do you have any browser extensions? What browser and OS are you using? Can you reproduce it in other browsers or other computers with the same keyboard?

**Comment by peksipatongeis** [comment]
Hi Evan,

I'm running macOS Catalina now, and it was the same with Mojave before I updated. Tried it with 3 different browsers and they all have the same problem. I asked my colleague to try it out and he has the same problem.

Browsers tested:
- Chrome 77.0.3865.120
- Firefox 70.0
- Safari 13.0.2 (15608.2.30.1.1)

You should be able to reproduce this by switching to a nordic keyboard layout, I'm using Finnish layout. I can type these characters with US / UK layout but the keys required to type them out are completely different on Nordic/Finnish layout.

[ = Option + 8
] = Option + 9
{ = Option + Shift + 8
} = Option + Shift + 9

**Comment by evancz** [comment]
Alright, it should be working based on the changes in https://github.com/evancz/guide.elm-lang.org/commit/4109eae8b0bad3d0e315e8ded97becfa6dc4d17f

You can confirm by trying any page in the guide, but be sure you are not getting cached versions of things!

Thank you for letting me know about this!
