### ISSUE TITLE
Effects chapter could be more clear

### ISSUE THREAD

**Issue by lzrski** [evancz/guide.elm-lang.org#28]
Hello, and thanks for all the hard work you are putting into Elm. I'm very excited to learn this beautiful language.

I must admit that while reading the tutorial I got stuck for a while in the [chapter about effects](http://guide.elm-lang.org/architecture/effects/). The prose is very clear, but code samples seem to miss the following:
- Reader must switch from `Html.App.beginnerProgram` to `Html.App.program`
- How to implement subscriptions function using `Sub.none`

Eventually I got it by looking at the examples in `try Elm`, but IMO it would be helpful to give more complete example in the tutorial itself.

**Comment by evancz** [comment]
Added this to the #93 meta issue to track a bunch of things folks find confusing.
