### ISSUE TITLE
Mention how to call a JS function *with no argument* via a port

### ISSUE THREAD

**Issue by jvoigtlaender** [evancz/guide.elm-lang.org#34]
Currently http://guide.elm-lang.org/interop/javascript.html#ports gives this example for an Elm-to-JS port:

``` elm
port check : String -> Cmd msg
```

to be used when aiming to call a JS function that takes a string argument.

A possible question arising at that point is what to do if the JS function one wants to call does not take an argument. A wrong assumption one can make is that one then simply defines a port in similar format as above but without argument:

``` elm
port name : Cmd msg
```

That does not work, though. A concrete case where someone arrived at that wrong assumption and then was stuck is [here on the mailing list](https://groups.google.com/d/msg/elm-dev/552FrqNm3s4/sPIwi6pQCwAJ).

I propose that the guide mentions what to do in that case, namely define

``` elm
port name : () -> Cmd msg
```

and call the function via expression `name ()`.

That would also be a good opportunity in the guide to explain `()` as both type and value, which is not otherwise happening in the guide, but occurs frequently as question from beginners, on the mailing list etc. (See http://faq.elm-community.org/#what-does--mean-1, for example.)

---

The underlying question here seems to be a reappearing one:
- https://groups.google.com/d/msg/elm-discuss/myMx01zbhDU/DnKi6MJwAQAJ
- https://groups.google.com/d/msg/elm-discuss/BFS03hbiT6A/XwOmNktAAwAJ
- https://github.com/elm-lang/error-message-catalog/issues/172
- https://groups.google.com/d/msg/elm-dev/552FrqNm3s4/GCSuLCajBgAJ
- ...

**Comment by jvoigtlaender** [comment]
The underlying question here seems to be a reappearing one: https://groups.google.com/d/msg/elm-discuss/myMx01zbhDU/DnKi6MJwAQAJ.

**Comment by naddeoa** [comment]
This actually helped me out, thanks a lot

**Comment by catz** [comment]
It helped me too. But I'd like to read the reason on why we just can't use following? () is a bit confusing.

`port name : Cmd msg`

**Comment by evancz** [comment]
Tracking in #93, though the solution is probably to make `port name : Cmd msg` work since giving it unit is pretty pointless. Can fix by improving the section on ports or by improving language.
