### ISSUE TITLE
Can mention why type annotations are useful

### ISSUE THREAD

**Issue by deepak** [evancz/guide.elm-lang.org#45]
http://guide.elm-lang.org/types/reading_types.html says

> People can make mistakes in type annotations, so what happens if they say the wrong thing? Well, the compiler does not make mistakes, so it still figures out the type on its own. It then checks that your annotation matches the real answer. In other words, the compiler will always verify that all the annotations you add are correct.

As a beginner this raises the question, why add type annotations in the first place, if the compiler is going to catch it for us ?

I guess it is because we are freezing the inferred types. 
and the advantage is that compiler can throw an error if our assumptions change tomorrow

so can mention why type annotations are needed/useful ?

**Comment by evancz** [comment]
Tracking in #93. Thank you for the feedback!
