### ISSUE TITLE
The description of Random.generate introduces too many concepts and then does not explain them.

### ISSUE THREAD

**Issue by RJWoodhead** [evancz/guide.elm-lang.org#54]
When I was reading the "Random" page, as a newbie, the explanation of how the Random.generate works had me scratching my head for quite some time.

The problem is that it introduces too many new concepts without explanation.

You've got: function arguments in (parens), placeholder types (a -> msg), and there's no proper explanation of what Random.generate actually produces -- even if you figure out that it's a Cmd Msg, it's not clear that the _value_ is NewFace [integer].

I've attempted to rewrite the section to break it down and explain the concepts, but I hesitate to make a pull request because I'm still not sure I've gotten the concepts right.

Thus, I post it below for comments and suggestions - hopefully my confusion will serve some purpose.

``` elm
Random.generate : (a -> msg) -> Random.Generator a -> Cmd msg
```

There are a few new concepts in this line of code, so let's break it down in detail!

`Random.generate` has two arguments. The first, (a -> msg), is a **function** that has an argument of some type `a` and returns some other type `msg`; these are placeholders that will be filled in as we go. The second is a **generator** -- a recipe for producing certain types of random values; the `a` in its type must match the `a` in the first argument. The function returns a `Cmd msg`, and likewise, the `msg` must match the `msg` in the first argument.

Looking back at our definition of `Msg`, another way to think of `NewFace` is that it is a function that takes an `Int` argument and returns a `Msg`. In other words:

``` elm
NewFace : Int -> Msg
```

So Elm knows that `a` must be the type `Int` and `msg` must be the type `Msg`, which means that the second argument to `Random.generate` must be of type `Random.Generate Int`, which is exactly how `Random.int` is defined:

``` elm
Random.int : Int -> Int -> Random.Generator Int
```

You provide a lower and upper bound on the integer, and now you have a generator that produces integers in that range!

Finally, since Elm knows that `msg` must be of type `Msg`, the result of Random.generate is of type `Cmd Msg`, and (this is the clever bit) the value is `NewFace <random integer>`!

Whew! Now we can click and see the number flip to some new value!

**Comment by evancz** [comment]
Tracking in #93. When revising the structure to introduce things in a better way, I will be able to refer to the notes you shared here. Thank you!
