### ISSUE TITLE
reuse/checkboxes.html views are not using the model

### ISSUE THREAD

**Issue by kevinrenskers** [evancz/guide.elm-lang.org#55]
Should the view examples in https://guide.elm-lang.org/reuse/checkboxes.html not use the actual model to toggle the checkboxes on/off? I understand that the focus is on something else in that chapter, but it would make sense to have working examples. At least I was a bit tripped up at first, since the model and update function are defined but then the model isn't used in the view.

**Comment by evancz** [comment]
I just did a rewrite of the guide, and this section did not make it through. So this is resolved in the sense that I found other ways to try to get the point across.
