### ISSUE TITLE
random won't compile before subscriptions are specified

### ISSUE THREAD

**Issue by willnwhite** [evancz/guide.elm-lang.org#6]
There's no mention of subscriptions before "At this point, it is possible to wire it all up and take a look." in random.md, and App.program needs a subscriptions argument.

**Comment by lb-** [comment]
Had the same issue here, when completing the 'Phase One - The Bare Minimum' there is no mention of imports (which I guessed) but then nothing would load, the text states 'At this point, it is possible to wire it all up and take a look'.

I tried to put in.
```
main =
  Html.beginnerProgram { model = model, view = view, update = update }
```

But it requires model to be defined, but we are using init in this example up to this point.

Basically same issue as above, but got me stumped for a bit.

**Comment by lb-** [comment]
It appears there is only a `Html.beginnerProgram` and `Html.Program` meaning that the jump to a program with init, implies subscriptions are needed.

I like how the guide breaks this part up into phase one, but maybe it would be good to explain a bit about `main' and its role on this page.

https://guide.elm-lang.org/architecture/effects/

I see now that this is the literal main program to be run from a file.

Anyway, thanks for all the hard work, I hope this helps.

**Comment by evancz** [comment]
The book was significantly revised in an attempt to introduce concepts like this in a better order.
