### ISSUE TITLE
The guide on JavaScript interop should explain port function type definitions

### ISSUE THREAD

**Issue by halfzebra** [evancz/guide.elm-lang.org#75]
The part about [Ports](https://guide.elm-lang.org/interop/javascript.html#ports) says that incoming and outgoing ports have a generic type definition for messages:

```elm
-- port for sending strings out to JavaScript
port check : String -> Cmd msg

-- port for listening for suggestions from JavaScript
port suggestions : (List String -> msg) -> Sub msg
```

This part never explained in the guide and it's quite easy to get confused by `Cmd msg` and `Sub msg`.

The guide should mention that Subscriptions have generic type definition annotation for messages by design for better reusability outside of the module. The outgoing command has a generic type because it never sends messages and it's also easier to reuse it without having to `Cmd.map` it every time you use it outside of the module.

The compiler message is not very helpful.

> But you need to use the particular format described here:
> <http://guide.elm-lang.org/interop/javascript.html#ports>

Here is my stab on this:

>     Note, that you can not specify the exact message type of port commands.
> 
>     Both port functions can be exported and used outside of the module.
>     Since output does not emit any messages, we have type annotation definition with a generic `msg`,
>     so it's easier to use it outside of this module
>     and you don't have to use Cmd.map to re-map a non-existing message type.
> 
>     The subscription as well can be used outside of this module,
>     you can use any message type to receive messages from the port.

I'll send a PR if this makes sense.

Any feedback is very welcome!

**Comment by evancz** [comment]
I agree that the fix is to make the compiler give a better warning. If you just copy paste the same content into https://github.com/elm-lang/error-message-catalog/issues it will be there for the next time I take a pass over type errors. This one is actually quite a bit more complex to do than just writing the text.
