### ISSUE TITLE
Core language: Prompt readers to add two spaces before new line

### ISSUE THREAD

**Issue by jsms90** [evancz/guide.elm-lang.org#78]
Despite the fact that
> over9000 powerLevel = \
> |   if powerLevel > 9000 then "It's over 9000!!!" else "meh"
> <function>

clearly has a double space before the new line, I (and a few other newbies) didn't register this and struggled briefly with:

> over9000 powerLevel = 
> -- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm
> 
> The = operator is reserved for defining variables. Maybe you want == instead? Or
maybe you are defining a variable, but there is whitespace before it?

Might be useful just to prompt readers to add the spaces before the new line?

**Comment by evancz** [comment]
#51 attempts to address this in a way that I think makes more sense. If there is something visual there, people will try to put that visual thing in I think. Anyway, thanks for bringing this to my attention!
