### ISSUE TITLE
Add Github Fork button for easier access to edit the guide

### ISSUE THREAD

**Issue by madnight** [evancz/guide.elm-lang.org#81]
This is how the top right icon bar at https://guide.elm-lang.org/ looks right now. 

![](https://i.imgur.com/ZzdYGYd.png) 

Suggestion add a Github symbol that redirects to this repository https://github.com/evancz/guide.elm-lang.org/ for easier forking -> editing -> pull requesting without searching for this repo on google.

**Comment by evancz** [comment]
The chrome on the book is created by gitbook.com which hosts the content. We would need to change the hosting and figure out how to generate the whole book from the backing markdown to change this as far as I know.
