### ISSUE TITLE
Properly breaking down the first program from the guide

### ISSUE THREAD

**Issue by niwolive** [evancz/guide.elm-lang.org#87]
The first full Elm progam of the guide is at [The Elm Architecture » User inputs » Buttons](https://guide.elm-lang.org/architecture/user_input/buttons.html). This page starts by showing code stating that it will be broken down afterwards, however the following code:

```elm
main =
  Html.beginnerProgram { model = model, view = view, update = update }
```
Is not explained. Also, taking the initiative to go over to the documentation for [the `beginnerProgram` method of the `Html` package](http://package.elm-lang.org/packages/elm-lang/html/latest/Html#beginnerProgram) doesn't gives much more insight as we are « gracefully » referred back to the guide:

> Read about The Elm Architecture to learn how to use this. Just do it. [...]

As I haven't read further at this point, the answer might come afterwards, however I would recommend to give more insights at this stage as the lack of information might deter people from pursuing reading the guide.

**Comment by evancz** [comment]
Tracking in #93. Thank you for sharing this experience and perspective!
