### ISSUE TITLE
"Websockets" chapter missing install step for websockets library

### ISSUE THREAD

**Issue by adsteel** [evancz/guide.elm-lang.org#92]
The [websockets chapter](https://guide.elm-lang.org/architecture/effects/web_sockets.html) doesn't walk you through installing the websocket package.

```sh
$ elm-package install elm-lang/websocket
```

**Comment by evancz** [comment]
There is not a websockets page in the current revision. If it is added back, the convention I am using is to talk about the dependencies and then include the code in full.
