### ISSUE TITLE
Adding more info to example in "Decoding Objects" section (suggestion)

### ISSUE THREAD

**Issue by justin-calleja** [evancz/guide.elm-lang.org#96]
In the following:

```
> import Json.Decode exposing (..)

> type alias Point = { x : Int, y : Int }

> Point
<function> : Int -> Int -> Point

> pointDecoder = map2 Point (field "x" int) (field "y" int)
<decoder> : Decoder Point

> decodeString pointDecoder """{ "x": 3, "y": 4 }"""
Ok { x = 3, y = 4 } : Result String Point
```

It was not immediately apparent that `map2` takes a `Point` and returns a `Decoder Int -> Decoder Int -> Decoder Point`.

Running `map2` in the REPL gives:

```
> map2
<function>
    : (a -> b -> value)
      -> Json.Decode.Decoder a
      -> Json.Decode.Decoder b
      -> Json.Decode.Decoder value
```

I initially thought that meant the first argument to `map2` had to be a `Decoder a` and since `Point` is not a `Decoder` ... I was struggling to make any sense of this.

Just a thought. If you think that section could use more explanation re this point, I'd be happy to write a PR.

**Comment by evancz** [comment]
The new page on JSON should be better. I tried to introduce decoders in a better way!
