### ISSUE TITLE
Mention Extensible Record Types

### ISSUE THREAD

**Issue by mltsy** [evancz/guide.elm-lang.org#98]
Wow!  I've recently finished a prototype for a fairly complex product with an Elm UI and *just* found out about extensible record types this morning! (even after having had problems where they would clearly be the best answer, and asking for advice in Slack about how to address them) - I can't believe I haven't heard of these before (and clearly I didn't look hard enough or something).

Extensible Record Types seem like such a useful and powerful feature (at least in my opinion) that they deserve a mention in the guide, even if it's just to say "Record types can be made extensible for complex use cases - see docs for more information." :smile:

**Comment by evancz** [comment]
I do not want to add more documentation about this at this time. It is important that you know all the record fields statically so you can compile to offsets, rather than having a dynamic lookup table, so that is my main priority on this topic.

**Comment by mltsy** [comment]
Oh, so you're saying you may remove extensible record types, making this documentation obsolete?  (Or else... what do you mean?)
